// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickProFixer.Data;

#nullable disable

namespace quickprofixer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250127220855_RemoveRequiredFromFixer")]
    partial class RemoveRequiredFromFixer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuickProFixer.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LGA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Landmark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine = "123 Main St",
                            Country = "Nigeria",
                            LGA = "Portharcourt",
                            State = "Rivers",
                            Town = "Portharcourt"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine = "456 Elm St",
                            Country = "Nigeria",
                            LGA = "Portharcourt",
                            State = "Rivers",
                            Town = "Portharcourt"
                        },
                        new
                        {
                            Id = 3,
                            AddressLine = "789 Pine St",
                            Country = "Nigeria",
                            LGA = "Portharcourt",
                            State = "Rivers",
                            Town = "Portharcourt"
                        },
                        new
                        {
                            Id = 4,
                            AddressLine = "101 Maple St",
                            Country = "Nigeria",
                            LGA = "Eleme",
                            State = "Rivers",
                            Town = "Eleme"
                        },
                        new
                        {
                            Id = 5,
                            AddressLine = "202 Oak St",
                            Country = "Nigeria",
                            LGA = "Eleme",
                            State = "Rivers",
                            Town = "Eleme"
                        },
                        new
                        {
                            Id = 6,
                            AddressLine = "303 Birch St",
                            Country = "Nigeria",
                            LGA = "Eleme",
                            State = "Rivers",
                            Town = "Eleme"
                        },
                        new
                        {
                            Id = 7,
                            AddressLine = "404 Cedar St",
                            Country = "Nigeria",
                            LGA = "Portharcourt",
                            State = "Rivers",
                            Town = "Portharcourt"
                        });
                });

            modelBuilder.Entity("QuickProFixer.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("QuickProFixer.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FixerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("QuoteId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("FixerId");

                    b.HasIndex("QuoteId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("QuickProFixer.Models.ClientRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FixerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("FixerId");

                    b.ToTable("ClientRatings");
                });

            modelBuilder.Entity("QuickProFixer.Models.FixRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FixerId")
                        .HasColumnType("nvarchar(450)");

                    b.PrimitiveCollection<string>("FixerIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PreferredSchedule")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupportingDocumentId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("SupportingFiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupportingImageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("FixerId");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("SupportingDocumentId");

                    b.HasIndex("SupportingImageId");

                    b.ToTable("FixRequests");
                });

            modelBuilder.Entity("QuickProFixer.Models.FixerRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FixerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("FixerId");

                    b.ToTable("FixerRatings");
                });

            modelBuilder.Entity("QuickProFixer.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FixerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ClientId");

                    b.HasIndex("FixerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("QuickProFixer.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientPaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FixerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FixerPaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ClientId");

                    b.HasIndex("FixerId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("QuickProFixer.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FixRequestId")
                        .HasColumnType("int");

                    b.Property<string>("FixerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SupportingDocumentId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("SupportingFiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupportingImageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("FixRequestId");

                    b.HasIndex("FixerId");

                    b.HasIndex("SupportingDocumentId");

                    b.HasIndex("SupportingImageId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("QuickProFixer.Models.QuoteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuoteId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteItems");
                });

            modelBuilder.Entity("QuickProFixer.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Plumbing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electricals"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Masonry"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tiling"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Screeding"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Painting"
                        });
                });

            modelBuilder.Entity("QuickProFixer.Models.SupportingFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SupportingFiles");
                });

            modelBuilder.Entity("QuickProFixer.Models.Client", b =>
                {
                    b.HasBaseType("QuickProFixer.Models.ApplicationUser");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AddressId");

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "client1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f0edb018-497d-421d-831b-3c8c65258a21",
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            MiddleName = "",
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHN.DOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdvC2XhzDarnspzheXAzTb0vPGOcqok9Yt0oIDvjP5wJ9V9kguwLS3RNVl4v60OzA==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "389813e7-14f2-42eb-98e2-262e0a8bdf44",
                            TwoFactorEnabled = false,
                            UserName = "john.doe@example.com",
                            AddressId = 6,
                            CurrentRole = "Client",
                            ImgUrl = "",
                            IsVerified = true,
                            Location = "Eleme",
                            VerificationDocument = "doc1.pdf"
                        },
                        new
                        {
                            Id = "client2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5096ad1a-2f4e-473c-927d-d3e31a7e7a7e",
                            Email = "jane.doe@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            MiddleName = "",
                            NormalizedEmail = "JANE.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JANE.DOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEculRoIhX2oa5sDymPxYXYt1iHqdMNe34wfXcFwanmeSTU/DeexM5Qnp3G6jtoLtQ==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "4bb640d1-09d9-4771-bf9c-5d16848173db",
                            TwoFactorEnabled = false,
                            UserName = "jane.doe@example.com",
                            AddressId = 7,
                            CurrentRole = "Client",
                            ImgUrl = "",
                            IsVerified = true,
                            Location = "Portharcourt",
                            VerificationDocument = "doc2.pdf"
                        });
                });

            modelBuilder.Entity("QuickProFixer.Models.Fixer", b =>
                {
                    b.HasBaseType("QuickProFixer.Models.ApplicationUser");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Certifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Portfolio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Reviews")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AddressId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Fixers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fixer1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fdca1d12-f68b-4fdc-9474-065d54320271",
                            Email = "alice.smith@example.com",
                            EmailConfirmed = true,
                            FirstName = "Alice",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            MiddleName = "",
                            NormalizedEmail = "ALICE.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "ALICE.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEChlH7mBBukQZnx7h41h9jYKUv9/jrplBOG1MaT7nHQoU7y9dGlm+VQc0hyCKLv5FQ==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "0b0cdbe8-b3e8-49d5-b031-cf978b70a204",
                            TwoFactorEnabled = false,
                            UserName = "alice.smith@example.com",
                            AddressId = 1,
                            Certifications = "Certified Electrician",
                            CurrentRole = "Fixer",
                            ExperienceYears = 5,
                            ImgUrl = "",
                            IsAvailable = true,
                            IsVerified = true,
                            Location = "Portharcourt",
                            Portfolio = "portfolio1.pdf",
                            Rate = 40.0m,
                            RateType = "Per Hour",
                            Rating = 4.7999999999999998,
                            Reviews = "Great work",
                            SpecializationId = 2,
                            VerificationDocument = "doc3.pdf"
                        },
                        new
                        {
                            Id = "fixer2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9c77147c-9f3b-4e15-80bf-a4aac7f4d2ca",
                            Email = "bob.johnson@example.com",
                            EmailConfirmed = true,
                            FirstName = "Bob",
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            MiddleName = "",
                            NormalizedEmail = "BOB.JOHNSON@EXAMPLE.COM",
                            NormalizedUserName = "BOB.JOHNSON@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOdfLuZGtjUs5ib9OgTOzY09PE4gXlVuThJ8LNdrYJR+W5z0zhzq+txvE5ij7zfP/A==",
                            PhoneNumber = "2345678901",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "81fd005a-4fc9-424c-a3ac-bff457dd6c63",
                            TwoFactorEnabled = false,
                            UserName = "bob.johnson@example.com",
                            AddressId = 2,
                            Certifications = "Certified Plumber",
                            CurrentRole = "Fixer",
                            ExperienceYears = 10,
                            ImgUrl = "",
                            IsAvailable = true,
                            IsVerified = true,
                            Location = "Portharcourt",
                            Portfolio = "portfolio2.pdf",
                            Rate = 50.0m,
                            RateType = "Per Hour",
                            Rating = 4.5,
                            Reviews = "Excellent service",
                            SpecializationId = 1,
                            VerificationDocument = "doc4.pdf"
                        },
                        new
                        {
                            Id = "fixer3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9310bdf3-116e-4acc-a558-1c6ab7d9f94a",
                            Email = "charlie.brown@example.com",
                            EmailConfirmed = true,
                            FirstName = "Charlie",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            MiddleName = "",
                            NormalizedEmail = "CHARLIE.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "CHARLIE.BROWN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPxri3W09f9/2e/mtTlOnwHeywehmRDpXsq7Bj5NV9LFkHHsSGy4yN7TFV56uYgqfw==",
                            PhoneNumber = "3456789012",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e481da8b-01ae-4a95-8066-df2144741a81",
                            TwoFactorEnabled = false,
                            UserName = "charlie.brown@example.com",
                            AddressId = 3,
                            Certifications = "Certified Mason",
                            CurrentRole = "Fixer",
                            ExperienceYears = 8,
                            ImgUrl = "",
                            IsAvailable = true,
                            IsVerified = true,
                            Location = "Portharcourt",
                            Portfolio = "portfolio3.pdf",
                            Rate = 45.0m,
                            RateType = "Per Hour",
                            Rating = 4.7000000000000002,
                            Reviews = "Highly skilled",
                            SpecializationId = 3,
                            VerificationDocument = "doc5.pdf"
                        },
                        new
                        {
                            Id = "fixer4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "899373f3-20ab-4d23-a859-9ca48010750d",
                            Email = "david.williams@example.com",
                            EmailConfirmed = true,
                            FirstName = "David",
                            LastName = "Williams",
                            LockoutEnabled = false,
                            MiddleName = "",
                            NormalizedEmail = "DAVID.WILLIAMS@EXAMPLE.COM",
                            NormalizedUserName = "DAVID.WILLIAMS@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAefcqXfjG+IM3oVklgSYGw7bmmmpqc/RBvJtyCoha8HePIr0vKEUJEXO+vVA8dkUg==",
                            PhoneNumber = "4567890123",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "2d1f60c0-b33a-445d-9104-e4805fab2ddb",
                            TwoFactorEnabled = false,
                            UserName = "david.williams@example.com",
                            AddressId = 4,
                            Certifications = "Certified Tiler",
                            CurrentRole = "Fixer",
                            ExperienceYears = 6,
                            ImgUrl = "",
                            IsAvailable = true,
                            IsVerified = true,
                            Location = "Eleme",
                            Portfolio = "portfolio4.pdf",
                            Rate = 42.0m,
                            RateType = "Per Hour",
                            Rating = 4.5999999999999996,
                            Reviews = "Excellent tiling",
                            SpecializationId = 4,
                            VerificationDocument = "doc6.pdf"
                        },
                        new
                        {
                            Id = "fixer5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3cdc6435-e271-4abf-a060-8b48bfa0a6d8",
                            Email = "eve.davis@example.com",
                            EmailConfirmed = true,
                            FirstName = "Eve",
                            LastName = "Davis",
                            LockoutEnabled = false,
                            MiddleName = "",
                            NormalizedEmail = "EVE.DAVIS@EXAMPLE.COM",
                            NormalizedUserName = "EVE.DAVIS@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL5AY/YtAIuk46oJjsztEGjMhVXrcGuV1lfhR0u+VAOxXSdVFKOD37kW4AEC1IufUg==",
                            PhoneNumber = "5678901234",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "3464786e-4e49-46fe-81ce-86c223198527",
                            TwoFactorEnabled = false,
                            UserName = "eve.davis@example.com",
                            AddressId = 5,
                            Certifications = "Certified Screeder",
                            CurrentRole = "Fixer",
                            ExperienceYears = 7,
                            ImgUrl = "",
                            IsAvailable = true,
                            IsVerified = true,
                            Location = "Eleme",
                            Portfolio = "portfolio5.pdf",
                            Rate = 48.0m,
                            RateType = "Per Hour",
                            Rating = 4.9000000000000004,
                            Reviews = "Top-notch screeding",
                            SpecializationId = 5,
                            VerificationDocument = "doc7.pdf"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuickProFixer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuickProFixer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuickProFixer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuickProFixer.Models.Booking", b =>
                {
                    b.HasOne("QuickProFixer.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Fixer", "Fixer")
                        .WithMany()
                        .HasForeignKey("FixerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Quote", "Quote")
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Fixer");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("QuickProFixer.Models.ClientRating", b =>
                {
                    b.HasOne("QuickProFixer.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Fixer", "Fixer")
                        .WithMany("ClientRatings")
                        .HasForeignKey("FixerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Fixer");
                });

            modelBuilder.Entity("QuickProFixer.Models.FixRequest", b =>
                {
                    b.HasOne("QuickProFixer.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Fixer", "Fixer")
                        .WithMany()
                        .HasForeignKey("FixerId");

                    b.HasOne("QuickProFixer.Models.Service", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.SupportingFile", "SupportingDocument")
                        .WithMany()
                        .HasForeignKey("SupportingDocumentId");

                    b.HasOne("QuickProFixer.Models.SupportingFile", "SupportingImage")
                        .WithMany()
                        .HasForeignKey("SupportingImageId");

                    b.Navigation("Address");

                    b.Navigation("Fixer");

                    b.Navigation("Specialization");

                    b.Navigation("SupportingDocument");

                    b.Navigation("SupportingImage");
                });

            modelBuilder.Entity("QuickProFixer.Models.FixerRating", b =>
                {
                    b.HasOne("QuickProFixer.Models.Client", "Client")
                        .WithMany("FixerRatings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Fixer", "Fixer")
                        .WithMany()
                        .HasForeignKey("FixerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Fixer");
                });

            modelBuilder.Entity("QuickProFixer.Models.Invoice", b =>
                {
                    b.HasOne("QuickProFixer.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Fixer", "Fixer")
                        .WithMany()
                        .HasForeignKey("FixerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Client");

                    b.Navigation("Fixer");
                });

            modelBuilder.Entity("QuickProFixer.Models.Payment", b =>
                {
                    b.HasOne("QuickProFixer.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Fixer", "Fixer")
                        .WithMany()
                        .HasForeignKey("FixerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Client");

                    b.Navigation("Fixer");
                });

            modelBuilder.Entity("QuickProFixer.Models.Quote", b =>
                {
                    b.HasOne("QuickProFixer.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.FixRequest", "FixRequest")
                        .WithMany()
                        .HasForeignKey("FixRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Fixer", "Fixer")
                        .WithMany()
                        .HasForeignKey("FixerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.SupportingFile", "SupportingDocument")
                        .WithMany()
                        .HasForeignKey("SupportingDocumentId");

                    b.HasOne("QuickProFixer.Models.SupportingFile", "SupportingImage")
                        .WithMany()
                        .HasForeignKey("SupportingImageId");

                    b.Navigation("Client");

                    b.Navigation("FixRequest");

                    b.Navigation("Fixer");

                    b.Navigation("SupportingDocument");

                    b.Navigation("SupportingImage");
                });

            modelBuilder.Entity("QuickProFixer.Models.QuoteItem", b =>
                {
                    b.HasOne("QuickProFixer.Models.Quote", "Quote")
                        .WithMany("Items")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("QuickProFixer.Models.Client", b =>
                {
                    b.HasOne("QuickProFixer.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("QuickProFixer.Models.Client", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("QuickProFixer.Models.Fixer", b =>
                {
                    b.HasOne("QuickProFixer.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("QuickProFixer.Models.Fixer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Service", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("QuickProFixer.Models.Quote", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("QuickProFixer.Models.Client", b =>
                {
                    b.Navigation("FixerRatings");
                });

            modelBuilder.Entity("QuickProFixer.Models.Fixer", b =>
                {
                    b.Navigation("ClientRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
