// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickProFixer.Data;

#nullable disable

namespace quickprofixer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250123153434_UpdateTableStructureAndSeedData")]
    partial class UpdateTableStructureAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuickProFixer.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("QuickProFixer.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FixerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("QuoteId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("FixerId");

                    b.HasIndex("QuoteId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("QuickProFixer.Models.ClientRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FixerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("FixerId");

                    b.ToTable("ClientRatings");
                });

            modelBuilder.Entity("QuickProFixer.Models.FixRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FixerId")
                        .HasColumnType("nvarchar(450)");

                    b.PrimitiveCollection<string>("FixerIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PreferredSchedule")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupportingDocumentId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("SupportingFiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupportingImageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FixerId");

                    b.HasIndex("SupportingDocumentId");

                    b.HasIndex("SupportingImageId");

                    b.ToTable("FixRequests");
                });

            modelBuilder.Entity("QuickProFixer.Models.FixerRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FixerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("FixerId");

                    b.ToTable("FixerRatings");
                });

            modelBuilder.Entity("QuickProFixer.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FixerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ClientId");

                    b.HasIndex("FixerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("QuickProFixer.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientPaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FixerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FixerPaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ClientId");

                    b.HasIndex("FixerId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("QuickProFixer.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FixRequestId")
                        .HasColumnType("int");

                    b.Property<string>("FixerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SupportingDocumentId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("SupportingFiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupportingImageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("FixRequestId");

                    b.HasIndex("FixerId");

                    b.HasIndex("SupportingDocumentId");

                    b.HasIndex("SupportingImageId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("QuickProFixer.Models.QuoteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuoteId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteItems");
                });

            modelBuilder.Entity("QuickProFixer.Models.SupportingFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SupportingFiles");
                });

            modelBuilder.Entity("QuickProFixer.Models.Client", b =>
                {
                    b.HasBaseType("QuickProFixer.Models.ApplicationUser");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "client1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d60b825c-b2c7-427a-80f2-ef754f78a08d",
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            MiddleName = "",
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHN.DOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6oZ+Il6m/CBpCjQKdyMI0TlhBWU1DyzM904VWcHStD5cRxgRGkCgVoKLTNHvmmGQ==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "534b4ab0-3ba2-403a-9022-95fa6de59525",
                            TwoFactorEnabled = false,
                            UserName = "john.doe@example.com",
                            Address = "123 Main St",
                            CurrentRole = "Client",
                            ImgUrl = "",
                            IsVerified = true,
                            Location = "Portharcourt",
                            VerificationDocument = "doc1.pdf"
                        },
                        new
                        {
                            Id = "client2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2c5e2fa0-cde4-4ef2-adad-972f77ea9d3e",
                            Email = "jane.doe@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            MiddleName = "",
                            NormalizedEmail = "JANE.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JANE.DOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOZoqyvbH5SIimhTh/36msXmuVmdILMvP3JcOzWyqQE4wy1x4CzcogOPefaQGW32UA==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a0f0511e-fae3-46a4-a649-72afcc1eea78",
                            TwoFactorEnabled = false,
                            UserName = "jane.doe@example.com",
                            Address = "456 Elm St",
                            CurrentRole = "Client",
                            ImgUrl = "",
                            IsVerified = true,
                            Location = "Portharcourt",
                            VerificationDocument = "doc2.pdf"
                        });
                });

            modelBuilder.Entity("QuickProFixer.Models.Fixer", b =>
                {
                    b.HasBaseType("QuickProFixer.Models.ApplicationUser");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Portfolio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Reviews")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specializations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Fixers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fixer1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "177b33e8-5f79-40cf-bf5b-c208529adc16",
                            Email = "alice.smith@example.com",
                            EmailConfirmed = true,
                            FirstName = "Alice",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            MiddleName = "",
                            NormalizedEmail = "ALICE.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "ALICE.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG0+tA5BG1+Ze0Wd6dAWGS4q6juGKaXDU8uwxrbV67HUa87gvVYWZjYDCaFW3kZuPw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "230a9aa3-31ba-4e62-b4bd-5255e4242b51",
                            TwoFactorEnabled = false,
                            UserName = "alice.smith@example.com",
                            Address = "789 Pine St",
                            Certifications = "Certified Electrician",
                            CurrentRole = "Fixer",
                            ExperienceYears = 5,
                            ImgUrl = "",
                            IsAvailable = true,
                            IsVerified = true,
                            Location = "Portharcourt",
                            Portfolio = "portfolio1.pdf",
                            Rate = 40.0m,
                            RateType = "Per Hour",
                            Rating = 4.7999999999999998,
                            Reviews = "Great work",
                            Specializations = "Electrical",
                            VerificationDocument = "doc3.pdf"
                        },
                        new
                        {
                            Id = "fixer2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "478901e6-86f5-4070-860a-dbc6cd62c8ce",
                            Email = "bob.johnson@example.com",
                            EmailConfirmed = true,
                            FirstName = "Bob",
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            MiddleName = "",
                            NormalizedEmail = "BOB.JOHNSON@EXAMPLE.COM",
                            NormalizedUserName = "BOB.JOHNSON@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDCQCcqhrKNBzp3vCuIR1OiiTW3XF9Z3K67wYIvxGXYufVKKe7o5X/k/oO95PDKwDQ==",
                            PhoneNumber = "2345678901",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "cd884783-ca55-41f6-af78-f79c4163fef5",
                            TwoFactorEnabled = false,
                            UserName = "bob.johnson@example.com",
                            Address = "101 Maple St",
                            Certifications = "Certified Plumber",
                            CurrentRole = "Fixer",
                            ExperienceYears = 10,
                            ImgUrl = "",
                            IsAvailable = true,
                            IsVerified = true,
                            Location = "Portharcourt",
                            Portfolio = "portfolio2.pdf",
                            Rate = 50.0m,
                            RateType = "Per Hour",
                            Rating = 4.5,
                            Reviews = "Excellent service",
                            Specializations = "Plumbing",
                            VerificationDocument = "doc4.pdf"
                        },
                        new
                        {
                            Id = "fixer3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f7ee293b-e00f-4c06-87b1-e452e0028012",
                            Email = "charlie.brown@example.com",
                            EmailConfirmed = true,
                            FirstName = "Charlie",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            MiddleName = "",
                            NormalizedEmail = "CHARLIE.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "CHARLIE.BROWN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAt/Q8zwOmH3jrjr41uiq++MalN+ufeglsNoUjJmAc1KKVCY96TOeGeVKHiE97DFhg==",
                            PhoneNumber = "3456789012",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "082c50db-9f16-4de3-aaed-a6e01db963b4",
                            TwoFactorEnabled = false,
                            UserName = "charlie.brown@example.com",
                            Address = "202 Oak St",
                            Certifications = "Certified Carpenter",
                            CurrentRole = "Fixer",
                            ExperienceYears = 8,
                            ImgUrl = "",
                            IsAvailable = true,
                            IsVerified = true,
                            Location = "Eleme",
                            Portfolio = "portfolio3.pdf",
                            Rate = 45.0m,
                            RateType = "Per Hour",
                            Rating = 4.7000000000000002,
                            Reviews = "Highly skilled",
                            Specializations = "Carpentry",
                            VerificationDocument = "doc5.pdf"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuickProFixer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuickProFixer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuickProFixer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuickProFixer.Models.Booking", b =>
                {
                    b.HasOne("QuickProFixer.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Fixer", "Fixer")
                        .WithMany()
                        .HasForeignKey("FixerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Quote", "Quote")
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Fixer");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("QuickProFixer.Models.ClientRating", b =>
                {
                    b.HasOne("QuickProFixer.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Fixer", "Fixer")
                        .WithMany("ClientRatings")
                        .HasForeignKey("FixerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Fixer");
                });

            modelBuilder.Entity("QuickProFixer.Models.FixRequest", b =>
                {
                    b.HasOne("QuickProFixer.Models.Fixer", "Fixer")
                        .WithMany()
                        .HasForeignKey("FixerId");

                    b.HasOne("QuickProFixer.Models.SupportingFile", "SupportingDocument")
                        .WithMany()
                        .HasForeignKey("SupportingDocumentId");

                    b.HasOne("QuickProFixer.Models.SupportingFile", "SupportingImage")
                        .WithMany()
                        .HasForeignKey("SupportingImageId");

                    b.Navigation("Fixer");

                    b.Navigation("SupportingDocument");

                    b.Navigation("SupportingImage");
                });

            modelBuilder.Entity("QuickProFixer.Models.FixerRating", b =>
                {
                    b.HasOne("QuickProFixer.Models.Client", "Client")
                        .WithMany("FixerRatings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Fixer", "Fixer")
                        .WithMany()
                        .HasForeignKey("FixerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Fixer");
                });

            modelBuilder.Entity("QuickProFixer.Models.Invoice", b =>
                {
                    b.HasOne("QuickProFixer.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Fixer", "Fixer")
                        .WithMany()
                        .HasForeignKey("FixerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Client");

                    b.Navigation("Fixer");
                });

            modelBuilder.Entity("QuickProFixer.Models.Payment", b =>
                {
                    b.HasOne("QuickProFixer.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Fixer", "Fixer")
                        .WithMany()
                        .HasForeignKey("FixerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Client");

                    b.Navigation("Fixer");
                });

            modelBuilder.Entity("QuickProFixer.Models.Quote", b =>
                {
                    b.HasOne("QuickProFixer.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.FixRequest", "FixRequest")
                        .WithMany()
                        .HasForeignKey("FixRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.Fixer", "Fixer")
                        .WithMany()
                        .HasForeignKey("FixerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickProFixer.Models.SupportingFile", "SupportingDocument")
                        .WithMany()
                        .HasForeignKey("SupportingDocumentId");

                    b.HasOne("QuickProFixer.Models.SupportingFile", "SupportingImage")
                        .WithMany()
                        .HasForeignKey("SupportingImageId");

                    b.Navigation("Client");

                    b.Navigation("FixRequest");

                    b.Navigation("Fixer");

                    b.Navigation("SupportingDocument");

                    b.Navigation("SupportingImage");
                });

            modelBuilder.Entity("QuickProFixer.Models.QuoteItem", b =>
                {
                    b.HasOne("QuickProFixer.Models.Quote", "Quote")
                        .WithMany("Items")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("QuickProFixer.Models.Client", b =>
                {
                    b.HasOne("QuickProFixer.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("QuickProFixer.Models.Client", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuickProFixer.Models.Fixer", b =>
                {
                    b.HasOne("QuickProFixer.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("QuickProFixer.Models.Fixer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuickProFixer.Models.Quote", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("QuickProFixer.Models.Client", b =>
                {
                    b.Navigation("FixerRatings");
                });

            modelBuilder.Entity("QuickProFixer.Models.Fixer", b =>
                {
                    b.Navigation("ClientRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
